### ISSUE TITLE
Use EU URL for Site Verify

### ISSUE THREAD

**Issue by sprankhub** [iMi-digital/magento2-friendly-captcha#19]
Currently, the `siteverify` call is done with a static URL:

https://github.com/iMi-digital/magento2-friendly-captcha/blob/390adb5c15881738de8e6f258db3db2d3fb30b8b/Model/Validate.php#L81

According to https://docs.friendlycaptcha.com/#/eu_endpoint, it is also possible to use the EU URL for the `siteverify` call. Hence, I think we should use the EU URL if `imi_friendly_captcha/general/eu_endpoint` is enabled.

**Comment by amenk** [comment]
yes, but see also https://github.com/iMi-digital/magento2-friendly-captcha/issues/11

We want to make the URLs fully configurable to also support other alternative servers, so we would need two string fields for widget and API URL. Or an additional option "custom URLs2.

We can introduce this a a breaking change and / or migrate configuration.

Are you interested to make a pull request? Otherwise we would probably tackle this, but it will take some time.

**Comment by sprankhub** [comment]
Yeah, I saw that...

For now, I would only make a PR for a simple "if EU endpoint is enabled, use EU URL for site verify" feature. This is already better than nothing IMHO. Right?

If you want to extend this even further in the future, fine for me. However, I do not have a use case for this now.

**Comment by amenk** [comment]
Ok fine with me, go ahead
