### ISSUE TITLE
Wrong Verification Response Processing

### ISSUE THREAD

**Issue by sprankhub** [iMi-digital/magento2-friendly-captcha#24]
We have the issue that fake customer accounts are still created even though we use this extension correctly. With the help of @amenk, I found out that there is an issue with the processing of the verification response:

https://github.com/iMi-digital/magento2-friendly-captcha/blob/06100b17b47b8a07f045c12b8a838fd052101ddd/Model/Validate.php#L84-L93

We only use the `success` result from the API if the curl status is 200. However, as shown in the [API docs](https://docs.friendlycaptcha.com/#/verification_api?id=the-verification-response), in quite some cases, the status is not 200, but should still be handled. The question is how strict we want to handle it:

* Should `secret_missing` pass or fail?
* Should `secret_invalid` pass or fail?
* Should `solution_missing` pass or fail? This definitely needs to fail, because otherwise, an attacker can simply remove the solution input field from the DOM and thereby bypass the check (this is what currently happens on our site).
* Should `bad_request` pass or fail?

IMHO, we should always use `$response['success']` if it is set and only fall back to `return true` if there is no such response.

@DanieliMi, @amenk, could you have a look and give feedback?

**Comment by DanieliMi** [comment]
@sprankhub back when we developed the module we decided to return `true` by default in favor of the real customer, so that they  can still use the site (in case we messed up by not configuring a secret for example). The case of `solution_missing` is definitely a case that we missed and should fail as we can see by your example.

I think we should fail on `solution_missing` and `bad_request` but still return `true` in case of a missing or invalid secret. A missing or invalid secret is a case of wrong configuration and in my opinion should not prevent real customers from using the site.

I think it might be more beneficial to add a warning to the adminhtml configuration in case of a missing secret. In case of an invalid secret my first idea was to send an email notification to a responsible person but I am not sure if that is a good idea. Do you have any idea for that?

**Comment by sprankhub** [comment]
> I think we should fail on `solution_missing` and `bad_request` but still return `true` in case of a missing or invalid secret. A missing or invalid secret is a case of wrong configuration and in my opinion should not prevent real customers from using the site.

Fine for me. Would you be able to fix this on short notice? Otherwise, I will try to send a PR.

> I think it might be more beneficial to add a warning to the adminhtml configuration in case of a missing secret. In case of an invalid secret my first idea was to send an email notification to a responsible person but I am not sure if that is a good idea. Do you have any idea for that?

It would be nice if on config save, the API connection would be checked. However, I think this is just a nice-to-have and not really necessary.

**Comment by sprankhub** [comment]
Here you go, @DanieliMi: https://github.com/iMi-digital/magento2-friendly-captcha/pull/25

**Comment by DanieliMi** [comment]
@sprankhub thank you very much for the fix! I just released it in [1.6.2](https://github.com/iMi-digital/magento2-friendly-captcha/releases/tag/1.6.2).

**Comment by sprankhub** [comment]
Thanks! It seems like the release is not marked as the latest one, though. Maybe you want to fix :)

**Comment by DanieliMi** [comment]
Thank you for the info! That's fixed :)
