### ISSUE TITLE
Incorrect Friendly Captcha validation (Product Ratings/Reviews not supported)

### ISSUE THREAD

**Issue by dfloerke** [iMi-digital/magento2-friendly-captcha#28]
Hello,

we get "Incorrect Friendly Captcha validation" on Product Ratings. But Friendly Captcha is not in the page and we cant stop the Validation for the Ratings in the Extension options.

**Comment by amenk** [comment]
Hi @dfloerke, thanks for the report.

The product reviews are currently not supported.
I think Friendly Captcha should be rendered on the review pages as well, otherwise SPAM would be likely (if it is just disabled, which is also currently not possible, thus tagging also as a "bug")

Are you able to provide a pull request to implement it?
It should be straight forward to implement it, similar to https://github.com/iMi-digital/magento2-friendly-captcha/pull/17/files 

PS: This repository is participating in the https://hacktoberfest.com/

**Comment by dfloerke** [comment]
Hi @amenk 
Could you make this change?

**Comment by amenk** [comment]
For the record: Which Magento version are you using?

Currently the change is not planned on our side, maybe we can find a way. You can contact me at a.menk at imi.de via email.

**Comment by amenk** [comment]
Pullrequest merged in RC: https://github.com/iMi-digital/magento2-friendly-captcha/releases/tag/2.0.0-rc.1
Please test :-)

**Comment by amenk** [comment]
included in 2.0.0
